### ISSUE TITLE
sauron not seeing any org-mod events

### ISSUE THREAD

**Issue by emacsomancer** [djcb/sauron#37]
For some reason, Sauron is not detecting any org-mode events.  When I start Sauron, I can that it's loaded the sauron-org module, but it doesn't issue notifications about any org-mode events (twitter and erc notifications work as expected). Is there something else I need to do to get sauron to see the org-mode events?

**Comment by phil-s** [comment]
Is your `sauron-min-priority` sufficient? Perhaps try (temporarily) `(setq sauron-min-priority most-negative-fixnum)`, and re-testing?

**Comment by xaxes** [comment]
Same here. that `setq` didn't help.
Here's my Sauron's configuration
```elisp
(require 'sauron)
(global-set-key (kbd "C-c s") 'sauron-toggle-hide-show)
(global-set-key (kbd "C-c t") 'sauron-clear)
(setq sauron-separate-frame nil)
(add-hook 'sauron-event-added-functions
	  (lambda (origin prio msg &optional props)
	    (when (>= prio 4)
	      (sauron-fx-notify "Sauron" msg 10))))
(setq sauron-min-priority most-negative-fixnum)
```

**Comment by djcb** [comment]
Does something show up in your sauron window when you evaluate: `(sr-org-handler-func "3" "10:05" "boo!")` ?
