### ISSUE TITLE
Can not get any notification for Elfeed (windows 7)

### ISSUE THREAD

**Issue by llcc** [djcb/sauron#41]
Hi, @djcb 

I am working on Windows 7. I tried to make it possible to get notifications for update of Elfeed. However, I never made it. 

I am trying to debug this things, but can not think of a good way to start. Thanks if you can give me some diagnose.

**Comment by branduren** [comment]
Hey @llcc 
I had the same problem on linux. The solution was to set sauron-min-priority to 1 or 2, like this:
~~~ lisp
 (setq sauron-min-priority 1)
~~~
In my case it had the default value of 3, and the sauron-prio-elfeed-default was set to 2. I'm not sure if the solution works for you, but you could give it a try.

**Comment by branduren** [comment]
ouh, if you set the sauron-min-priority to 1, erc will flood your sauron buffer. Instead try changing the sauron-elfeed-prio instead, it's actually stated in the [README.org](https://github.com/djcb/sauron#elfeed) file.

**Comment by djcb** [comment]
Thanks, @branduren.
