### ISSUE TITLE
Getting sauron to work across multiple Emacs instances

### ISSUE THREAD

**Issue by dakrone** [djcb/sauron#42]
Due to Emacs' unfortunate single-threaded nature, I have to run multiple
instances for all of the things that I do with Emacs.

I was wondering if it would be possible for Sauron to write events to a location
on disk that could be shared across multiple instances of Emacs? That way I
could see mail/twitter notifications, ERC mentions, and other events all in
whichever emacs I am currently in.

Any idea whether that's possible (or even desired?)

**Comment by djcb** [comment]
Well, you could add a function to `sauron-event-added-functions` that writes the event in some lisp blob to a file, and use file notifications (ie. `file-notify-add-watch`) in some new sauron backend specific for that. Alternatively, you could use dbus. All while avoiding update loops.

So yes, it's possible, but it would be a bit of work.
