### ISSUE TITLE
Interest in adding twitter mentions in sauron-twittering?

### ISSUE THREAD

**Issue by dakrone** [djcb/sauron#43]
Is there interest for adding @-mention support for twittering-mode, where a sauron alert can be raised if a new tweet comes in that mentions you?

If so, I can try to add this, I just don't want to add it if there isn't support (I'll add it in my own dotfiles then)

**Comment by djcb** [comment]
Sure, looks like an interesting extension.

**Comment by dakrone** [comment]
Awesome, I've opened a PR for this.
