### ISSUE TITLE
Proposition for sauron popup window

### ISSUE THREAD

**Issue by josuah** [djcb/sauron#47]
For its package [hydra](https://github.com/abo-abo/hydra/), @abo-abo wrote [lv.el](https://github.com/abo-abo/hydra/blob/master/lv.el).  It is a simple tool to display a message on the echo area, or rather at the top of the echo area.

Using it for sauron may be a solution, but it could also interfere with the hydra package.

Anyway, emacs need a solution for these kinds of buffers.  I hope you will find a solution (if not yet, it works for me), and in emacs 25, the `*completion*` buffer that comes by pressing tab without helm or ivy.

I did not really used this package much yet, but I really like it already!  Thank you!

PS: This could be nice in the github description string: :volcano:

**Comment by djcb** [comment]
Ah, thanks!
